//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizkasa.Bizlunch.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_TB_FRIENDSHIP
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int FriendId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual DB_TB_ACCOUNTS DB_TB_ACCOUNTS { get; set; }
        public virtual DB_TB_ACCOUNTS DB_TB_ACCOUNTS1 { get; set; }
    }
}
