//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bizkasa.Bizlunch.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_TB_ORDER_DETAIL
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string MenuItem { get; set; }
        public Nullable<decimal> MenuCost { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual DB_TB_ACCOUNTS DB_TB_ACCOUNTS { get; set; }
        public virtual DB_TB_ORDERS DB_TB_ORDERS { get; set; }
    }
}
